---
default: true

# Common repo-wide pragmatic defaults
# MD013: Line length - allow long lines but prefer reasonable limits
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033: Inline HTML - allow specific safe elements
MD033:
  allowed_elements: ["br", "details", "summary"]

# MD041: First line heading - not required for all markdown files
MD041: false

# MD024: Multiple headings with same content - allow if nesting differs
MD024:
  allow_different_nesting: true
