// ============================================================
// OmniQuest Media Inc. / iMagiNarratives Inc.
// © 2024–2026 OmniQuest Media Inc. All rights reserved.
// Proprietary and confidential. Unauthorized use prohibited.
// Governed by ZoneGPT (MaxZone / OQMIgpt) — Corpus v11
// ============================================================
//
// classify-docs.js — buckets every tracked markdown doc into
// CANONICAL / HISTORICAL / UNKNOWN so a human can ratify what is the source
// of truth and what is a spent point-in-time report safe to archive.
// PORTABLE + reproducible: run it in any repo to get the same classification.
//
// Buckets (this is "reports scope" — deliberately conservative):
//   CANONICAL  — pinned source-of-truth docs. Seeded from
//                .github/required-files.txt (*.md entries) + a built-in
//                authority set. NEVER an archival candidate.
//   HISTORICAL — spent point-in-time reports: anything under a report
//                directory (REPORT_BACK/, DIRECTIVES/DONE/, archive/) OR a
//                strong report-named file at repo root / docs/ / PROGRAM_CONTROL/.
//                These are the ONLY archival candidates at reports scope.
//   UNKNOWN    — everything else. Left ALONE; needs human judgement, not a bot.
//
// It writes no timestamp, so output is stable unless the doc set changes.
// Usage: node scripts/classify-docs.js            (writes docs/DOC_CLASSIFICATION.md)
//        node scripts/classify-docs.js --json      (prints JSON to stdout, no write)

/* eslint-disable no-console, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports -- portable CLI script (CommonJS; console is the interface) */
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = process.cwd();
const OUT = path.join('docs', 'DOC_CLASSIFICATION.md');

// Built-in authorities that are canonical in every OQMInc repo regardless of
// required-files.txt. Matched by basename or exact path.
const BUILTIN_CANONICAL = new Set([
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  'CHANGELOG.md',
  'SECURITY.md',
  'CODE_OF_CONDUCT.md',
]);

// Directories whose markdown is inherently a spent report.
const REPORT_DIRS = [
  'PROGRAM_CONTROL/REPORT_BACK/',
  'PROGRAM_CONTROL/DIRECTIVES/DONE/',
  'archive/',
];

// Basename patterns that mark a report/status snapshot. Only applied to docs at
// repo root, docs/, or PROGRAM_CONTROL/ so product content is never swept in.
const REPORT_NAME_RE =
  /(REPORT-BACK|-report|_REPORT|-REPORT|FINAL-|_SUMMARY|-SUMMARY|SWEEP|CLEANUP|HYGIENE|VALIDATION|DASHBOARD|STATUS|HOMESTRETCH|COMPLETION|RELEASE-NOTE|^AUDIT-\d|^PHASE[-_]|^P0\.)/i;

const REPORT_NAME_DIRS = ['', 'docs/', 'PROGRAM_CONTROL/']; // '' == repo root

function trackedMarkdown() {
  try {
    return execSync('git ls-files "*.md"', { cwd: ROOT, encoding: 'utf8' })
      .split('\n')
      .map((s) => s.trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

function loadPinnedCanonical() {
  const pinned = new Set();
  const rf = path.join(ROOT, '.github', 'required-files.txt');
  try {
    for (const line of fs.readFileSync(rf, 'utf8').split('\n')) {
      const f = line.trim();
      if (!f || f.startsWith('#')) continue;
      if (f.toLowerCase().endsWith('.md')) pinned.add(f);
    }
  } catch {
    /* no required-files.txt in this repo — fine */
  }
  return pinned;
}

function inAnyDir(file, dirs) {
  return dirs.some((d) => file.startsWith(d));
}

function atNameDir(file) {
  const dir = file.includes('/') ? file.slice(0, file.lastIndexOf('/') + 1) : '';
  return REPORT_NAME_DIRS.includes(dir);
}

function classify(files, pinned) {
  const buckets = { CANONICAL: [], HISTORICAL: [], UNKNOWN: [] };
  for (const f of files) {
    const base = f.slice(f.lastIndexOf('/') + 1);
    if (pinned.has(f) || BUILTIN_CANONICAL.has(base)) {
      buckets.CANONICAL.push(f);
    } else if (inAnyDir(f, REPORT_DIRS) || (atNameDir(f) && REPORT_NAME_RE.test(base))) {
      buckets.HISTORICAL.push(f);
    } else {
      buckets.UNKNOWN.push(f);
    }
  }
  for (const k of Object.keys(buckets)) buckets[k].sort();
  return buckets;
}

function renderMarkdown(buckets, pinnedCount) {
  const total = buckets.CANONICAL.length + buckets.HISTORICAL.length + buckets.UNKNOWN.length;
  const list = (arr) => (arr.length ? arr.map((f) => `- \`${f}\``).join('\n') : '_none_');
  // Summary rendered as a fenced block (Prettier-stable — a markdown table
  // would be column-padded by the formatter and churn against regeneration).
  return `# Doc Classification (generated)

<!-- Auto-generated by scripts/classify-docs.js. Do not edit by hand. -->

Reproducible triage of every tracked markdown doc, at **reports scope**: only
HISTORICAL docs are archival candidates. CANONICAL is pinned source-of-truth
(never archived). UNKNOWN is left alone pending human judgement.

\`\`\`text
CANONICAL   ${buckets.CANONICAL.length}   source of truth (${pinnedCount} pinned via required-files.txt) — never archived
HISTORICAL  ${buckets.HISTORICAL.length}   spent point-in-time reports — archival candidates
UNKNOWN     ${buckets.UNKNOWN.length}   needs human ratification — left alone
TOTAL       ${total}
\`\`\`

## CANONICAL — source of truth (do not archive)

${list(buckets.CANONICAL)}

## HISTORICAL — archival candidates (spent reports)

These are safe to \`git mv\` into \`archive/\` under the quarantine policy in
\`docs/SOURCE_OF_TRUTH.md\`. Git history preserves them regardless.

${list(buckets.HISTORICAL)}

## UNKNOWN — human ratification required

Not touched at reports scope. Promote to CANONICAL, mark SUPERSEDED, or leave.

${list(buckets.UNKNOWN)}
`;
}

function main() {
  const files = trackedMarkdown();
  const pinned = loadPinnedCanonical();
  const buckets = classify(files, pinned);

  if (process.argv.includes('--json')) {
    process.stdout.write(
      JSON.stringify(
        {
          counts: {
            CANONICAL: buckets.CANONICAL.length,
            HISTORICAL: buckets.HISTORICAL.length,
            UNKNOWN: buckets.UNKNOWN.length,
          },
          buckets,
        },
        null,
        2,
      ) + '\n',
    );
    return;
  }

  fs.writeFileSync(path.join(ROOT, OUT), renderMarkdown(buckets, pinned.size));
  console.log(
    `classify-docs: ${OUT} written — ` +
      `CANONICAL ${buckets.CANONICAL.length}, ` +
      `HISTORICAL ${buckets.HISTORICAL.length}, ` +
      `UNKNOWN ${buckets.UNKNOWN.length}.`,
  );
}

main();
